reduced chances of default ad being called
liam-middlebrook/csh-plug pull request #4
Opened 2017-08-07 01:59 UTC by sgreene570

Everything compiled, hopefully it doesn't break everything. No promises!

2017-08-07 04:19 UTC, liam-middlebrook requested changes
From a quick read I don't believe that this will decrease the amount of default ads that are shown. It looks like it might actually increase the number because line 47 as well as line 49 could choose a default ad.

2017-08-07 04:19 UTC, liam-middlebrook commented on plug.go
> +	if p.ViewsRemaining >= 0 {
nit: pls condense to single line body

2017-08-07 04:19 UTC, liam-middlebrook commented on plug.go
> +	for i := 0; i < len(plugs); i++ {
Can't this be compacted to a single for loop?

2017-08-07 15:13 UTC, sgreene570 commented
Totally missed the contradiction in line 49. I will add link lists to clean things up (I needed to declare arrays with fixed sizes, that's why I had 2 for loops).

2017-08-11 19:40 UTC, liam-middlebrook requested changes
fix the nits, otherwise lgtm!

2017-08-11 19:40 UTC, liam-middlebrook commented on plug.go
> +func (p Plug) isDefault() bool {
nit: pls capitalize the leading letter of a function

2017-08-11 19:40 UTC, liam-middlebrook commented on plug.go
> +	if pickDefault >= 85 && len(defaults) != 0{
nit: pls move the constant 85 to a `const int` at the top of the file

2017-08-11 20:49 UTC, sgreene570 commented
Fixed the nits.

2017-08-11 22:13 UTC, liam-middlebrook approved these changes
lgtm

2017-08-11 22:13 UTC, merged